//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject1.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}が異なっています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckCompare {
            get {
                return ResourceManager.GetString("CheckCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が不正な日付です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckDate {
            get {
                return ResourceManager.GetString("CheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が有効なメールアドレスではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckEmailAddress {
            get {
                return ResourceManager.GetString("CheckEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の値が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckEnumDataType {
            get {
                return ResourceManager.GetString("CheckEnumDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が{1}～{2}の範囲外です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckRange {
            get {
                return ResourceManager.GetString("CheckRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が不正な値です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckRegularExpression {
            get {
                return ResourceManager.GetString("CheckRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckRequired {
            get {
                return ResourceManager.GetString("CheckRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の文字数が最大長{1}文字より大きくなっています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckStringLength {
            get {
                return ResourceManager.GetString("CheckStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は不正なURLです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckUrl {
            get {
                return ResourceManager.GetString("CheckUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のドメイン名が&quot;nekoni.net&quot;ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDomainName {
            get {
                return ResourceManager.GetString("InvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退社年月日が入社年月日より小さい日付になっています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRetireDate {
            get {
                return ResourceManager.GetString("InvalidRetireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotUnique {
            get {
                return ResourceManager.GetString("NotUnique", resourceCulture);
            }
        }
    }
}
